version: "3.5"

services:
  mongo:
    image: mongo
    command: mongod --rest
    volumes:
    - "mongo-data:/data/db"
    ports:
    - "27017:27017"

  journal:
    image: node
    working_dir: "/app"
    entrypoint: "yarn"
    ports:
      - "3000:3000"
    volumes:
      - "./src/:/app/src"
      - "./package.json:/app/package.json"
      - "./yarn.lock:/app/yarn.lock"
      - "node_modules:/app/node_modules"

volumes:
  node_modules:
  mongo-data: