version: '3.5'

services:
  mongo:
    image: mongo
    command: mongod
    volumes:
    - 'mongo-data:/data/db'
    ports:
    - '27017:27017'
    networks:
      - journal

  modules:
    image: node:8.9.4
    working_dir: '/app'
    command: 'yarn'
    volumes:
    - './package.json:/app/package.json'
    - 'journal_modules:/app/node_modules'
    networks:
    - journal

  web:
    image: node:8.9.4
    links:
      - mongo
    working_dir: '/app'
    command: 'yarn run dc:start'
    ports:
      - '3000:3000'
    volumes:
      - './src/:/app/src'
      - './package.json:/app/package.json'
      - './yarn.lock:/app/yarn.lock'
      - './tsconfig.json:/app/tsconfig.json'
      - './webpack.config.js:/app/webpack.config.js'
      - 'journal_modules:/app/node_modules'
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - journal

networks:
  journal:
    driver: bridge

volumes:
  journal_modules:
  mongo-data: